[package]
name = "keyurses"
version = "0.1.0"
authors = ["Jacob Karlsson <jacob.karlsson95@gmail.com>"]

[dependencies]
cursive = { git = "https://github.com/gyscos/Cursive", branch = "on_edit" }
rand = "0.3.15"